# Generated by Django 3.0.3 on 2020-08-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0007_auto_20200325_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pin',
            field=models.IntegerField(choices=[(1, 'Да'), (2, 'Нет')], default=2),
        ),
    ]
