# Generated by Django 3.0.3 on 2020-09-10 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0008_article_pin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='pin',
        ),
    ]
